baseurl = "https://vaidhyanathan93.github.io/" # Hostname (and path) to the root.
title = "vaidhyanathan" # Site title.
theme = "coder" # Set the theme.
languagecode = "en" # The site’s language code.

paginate = 20 # Default number of pages per page in pagination.
canonifyurls = true # Enable to turn relative URLs into absolute.

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.

#disqusShortname = "yourdiscussshortname" # Enable or disable Disqus

[params] # theme parameters
    author = "Vaidhyanathan A" # Author's name.
    info = "Backend Desginer and developer" # Author's job title or info.
    description = "Vaidhyanathan's personal website" # Site description.
    keywords = "blog,developer,personal,backend,designer" # Site keywords.

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = true
    hideCopyright = true

    # Custom CSS
    custom_css = []

    # RTL support
    rtl = false

# Social links
[[params.social]]
    name = "About"
    weight = 1
    url = "/about/"
[[params.social]]
    name = "vaidhyanathan93@gmail.com"
    weight = 2
    url = "mailto:vaidhyanathan93@gmail.com"

# Menu links
[[menu.main]]
    name = "About"
    weight = 1
    url = "/about/"
